= CultureGraph Record Aggregator

image::https://jitpack.io/v/culturegraph/culturegraph-record-aggregator.svg[link="https://jitpack.io/#culturegraph/culturegraph-record-aggregator"]

A library that uses link:https://github.com/marc4j/marc4j[marc4j] to aggregate MARC21 records into a single record.

== Introduction

The CultureGraph project produces groups of records that could be identified by
comparing them using a rule based matching procedure.

The library targets the export of those identified records into a single record.

== Procedure

Assuming a collection of records as input:

* For each record _r_
1. Add the data field link:https://www.loc.gov/marc/authority/ad035.html[035] (contains a field link _fl_)
2. Mark each data field (exclude field 035 and link:http://www.loc.gov/marc/bibliographic/bd883.html[883]) in _r_ with the field link _fl_

* Collect all data fields from all records
1. Re-Enumerate all field links (ascending order)
2. Create a blank record _b_
** Set build number as control number (control field link:https://www.loc.gov/marc/authority/ad001.html[001])
** Set pre-defined cataloging agency (control field link:https://www.loc.gov/marc/authority/ad003.html[003])
3. Add all data fields to _b_
4. Return _b_


== Appendix

=== Example

The folder `example` contains three marcxml records and their aggregate.
